@extends('app')

@section('content')
    <div>
            <h1 class="h2 title">What is Machine Learning? A Definition.</h1><div style="font-size: 16px; margin-top: -1%; margin-bottom:20px;">Expert.ai Team - 6 May 2020</div><div class="entry-content"><p><img loading="lazy" class="aligncenter wp-image-122912 size-full" src="http://devexpertai.wpengine.com/wp-content/uploads/2017/03/machine-learning-definition.jpeg" alt="" srcset="https://www.expert.ai/wp-content/uploads/2017/03/machine-learning-definition.jpeg 1600w, https://www.expert.ai/wp-content/uploads/2017/03/machine-learning-definition-300x79.jpeg 300w, https://www.expert.ai/wp-content/uploads/2017/03/machine-learning-definition-1024x268.jpeg 1024w, https://www.expert.ai/wp-content/uploads/2017/03/machine-learning-definition-768x201.jpeg 768w, https://www.expert.ai/wp-content/uploads/2017/03/machine-learning-definition-1536x402.jpeg 1536w" sizes="(max-width: 1600px) 100vw, 1600px" width="1600" height="419"></p>
            <p>Machine learning is an application of artificial intelligence (AI) that provides systems the ability to automatically learn and improve from experience without being explicitly programmed. <strong>Machine learning focuses on the development of computer programs</strong> that can access data and use it to learn for themselves.</p>
            <p>The process of learning begins with observations or data, such as examples, direct experience, or instruction, in order to look for patterns in data and make better decisions in the future based on the examples that we provide. <strong>The primary aim is to allow the computers learn automatically</strong> without human intervention or assistance and adjust actions accordingly.</p>
            <p>But, using the classic algorithms of machine learning, text is considered as a sequence of keywords; instead, <strong>an approach based on semantic analysis mimics the human ability to understand the meaning of a text.</strong></p>
            <h3>Some Machine Learning Methods</h3>
            <p>Machine learning algorithms are often categorized as supervised or unsupervised.</p>
            <ul>
            <li><strong>Supervised machine learning algorithms </strong>can apply what has been learned in the past to new data using labeled examples to predict future events. Starting from the analysis of a known training dataset, the learning algorithm produces an inferred function to make predictions about the output values. The system is able to provide targets for any new input after sufficient training. The learning algorithm can also compare its output with the correct, intended output and find errors in order to modify the model accordingly.</li>
            <li>In contrast, <strong>unsupervised machine learning algorithms </strong>are used when the information used to train is neither classified nor labeled. Unsupervised learning studies how systems can infer a function to describe a hidden structure from unlabeled data. The system doesn’t figure out the right output, but it explores the data and can draw inferences from datasets to describe hidden structures from unlabeled data.</li>
            <li><strong>Semi-supervised machine learning algorithms</strong> fall somewhere in between supervised and unsupervised learning, since they use both labeled and unlabeled data for training – typically a small amount of labeled data and a large amount of unlabeled data. The systems that use this method are able to considerably improve learning accuracy. Usually, semi-supervised learning is chosen when the acquired labeled data requires skilled and relevant resources in order to train it / learn from it. Otherwise, acquiring unlabeled data generally doesn’t require additional resources.</li>
            <li><strong>Reinforcement machine learning algorithms </strong>is a learning method that interacts with its environment by producing actions and discovers errors or rewards. Trial and error search and delayed reward are the most relevant characteristics of reinforcement learning. This method allows machines and software agents to automatically determine the ideal behavior within a specific context in order to maximize its performance. Simple reward feedback is required for the agent to learn which action is best; this is known as the reinforcement signal.</li>
            </ul>
            <p>Machine learning enables analysis of massive quantities of data. While it generally delivers faster, more accurate results in order to identify profitable opportunities or dangerous risks, it may also require additional time and resources to train it properly. Combining machine learning with AI and cognitive technologies can make it even more effective in <strong><a href="https://expert.ai/fr/nl-suite/discover/">processing large volumes of information</a></strong>.</p>
            
    </div>
@endsection